"""generated applications models

Revision ID: 6385841db998
Revises: fd873c79fdb3
Create Date: 2022-09-11 02:16:15.583508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6385841db998'
down_revision = 'fd873c79fdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trials_quiz_id_fkey', 'trials', type_='foreignkey')
    op.create_foreign_key(None, 'trials', 'quizzes', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trials', type_='foreignkey')
    op.create_foreign_key('trials_quiz_id_fkey', 'trials', 'surveys', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
